config/routes.rb
Rails.application.routes.draw do

  resources :followings
  root "sessions#new"

  get "login" => "sessions#new", as: :new_session
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get "users" => "users#index"
  get 'users/:id' => 'users#show', as: :user
  get "signup" => "users#new", as: :new_user
  post "users" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"

  get "videos" => "videos#index"
  get "videos/new" => "videos#new", as: :new_video
  post "videos" => "videos#create"
  get "videos/:id" => "videos#show", as: :video
  get "videos/:id/edit" => "videos#edit", as: :edit_video
  patch "videos/:id" => "videos#update"
  delete "videos/:id" => "videos#destroy"

  get "users/:user_id/followings" => "followings#index"

end

app/models/following.rb
class Following < ActiveRecord::Base
	belongs_to :user
	belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	
	has_many :videos

	has_many :followings
	has_many :followers, :through => :followings
	has_many :inverse_followings, class_name:"Following", foreign_key:"follower_id"
	has_many :inverse_followers, :through => :inverse_followings, :source => :user

	has_secure_password

	has_attached_file :image, styles: { small: "33x33", med: "100x100", large: "200x200", default_url: "asset_path( 'pawn.jpg' )"  }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user
	has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user 

	def current_user 
  		@current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end	

	def require_user
		redirect_to login_path unless current_user
	end	


  protect_from_forgery with: :exception
  
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def index
    user = User.find(params[:user_id])
    @following = user.followings.find(params[:idm])
  end

  def create
    @following = current_user.followings.build(:follower_id => params[:follower_id])
    if @following.save
      flash[:notice] = "Now following"
      redirect_to current_user
    else
      flash[:notice] = "Unable to follow"
      redirect_to users_path
    end
  end

  def destroy
    @following = current_user.followings.find(params[:id])
    @following.destroy
    flash[:notice] = "Un-followed"
    redirect_to current_user
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:user_id, :follower_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		@user = User.find_by_email(params[:session][:email])
		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to videos_path
		else
			redirect_to login_path
		end	
	end

	def destroy
		session[:user_id] = nil
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@videos = @user.videos
	end	

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
			if @user.save
				session[:user_id] = @user.id
				redirect_to videos_path
			else
				redirect_to new_user_path
			end		
	end

	def edit
		@user = User.find(params[:id])
	end

	def update 
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			render :edit
		end

	end

	def destroy 
		@user = User.find(params[:id]) 
		@user.destroy 
		redirect_to users_path 

	end


	private
	def user_params
		params.require(:user).permit(:user_name,:email,:password,:password_confirmation,:image)
	end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	before_action :require_user, only: [:create, :update, :destroy]

	def index
		@videos = Video.all
		
	end

	def show
		@video = Video.find(params[:id])
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)
		@video.user_id = current_user.id

			if @video.save
				redirect_to videos_path
			else	
				render :new
			end
	end

	def edit
		@video = Video.find(params[:id])
	end

	def update 
		@video = Video.find(params[:id])
		if @video.update_attributes(video_params)
			redirect_to videos_path
		else
			render :edit
		end

	end

	def destroy 
		@video = Video.find(params[:id]) 
		@video.destroy 
		redirect_to videos_path 

	end

	private	

		def video_params
			params.require(:video).permit(:source,:title,:description,:user_id)
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following) do |f| %>
  <% if @following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
      <% @following.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :follower_id %><br>
    <%= f.number_field :follower_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form' %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p>Followers</p>
<% @following.each do |f| -%>
    <p>
        <%= f.user.user_name %>
    </p>
<% end -%>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form' %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @following.user_id %>
</p>

<p>
  <strong>Follower:</strong>
  <%= @following.follower_id %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html class="blur">
<head>
  <title>KILOS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <script src="//use.typekit.net/dbt7vos.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <nav> 
        <img src="<%= asset_path( 'Menu_Logo.png' ) %>" id="menu_logo">
        <!-- Brand and toggle get grouped for better mobile display -->
        <% if current_user %>
            <button type="button" class="btn btn-disabled dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="idThumb"><%= image_tag current_user.image.url(:small) %></span><span class="menu-hamburger"></span></button>
            <ul class="dropdown-menu" role="menu">
                <li role="presentation"><%= link_to current_user.user_name, current_user %></li>
                <li role="presentation"><%= link_to 'Edit Profile', edit_user_path(current_user.id) %></li>
                <!-- link to all profiles -->
                <li role="presentation"><%= link_to "Kilo Camp", users_path %></li>
                <li role="presentation"><%= link_to "Sign Out", logout_path, method: "delete" %></li>               
            </ul>
        <% else %>
            <button type="button" class="btn btn-disabled dropdown-toggle btn-lg" data-toggle="dropdown" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger"></span></button>
                <ul class="dropdown-menu" role="menu">
                    <li role="presentation"><%= link_to "Login", new_session_path %></li>
			        <li role="presentation"><%= link_to "Signup", new_user_path %></li>
                </ul>
	   <% end %>
    </nav>
<div class="wrap">
    <div class="pageHead">
        <img src="<%= asset_path( 'kiloCover.jpg' ) %>" class="hero">       
    </div>
    <div class="yield">
	   <%= yield %> 
    </div> 
</div>
</body>
</html>

<!-- 


// <script type="text/javascript">
// $(document).ready( function() {
//     $('.blur').blurjs({
//         source: '.blur',
//         radius: 100,
//         overlay: 'rgba(200,200,200,.5)'
//     });
// });
// </script>
=======
<script type="text/javascript">
$(document).ready( function() {
    $('.blur').blurjs({
        source: '.blur',
        radius: 100,
        overlay: 'rgba(200,200,200,.5)'
    });
});
</script>
 -->

app/views/users/edit.html.erb
<!-- auto update current user name, put into uppercase -->
<h2><%= @user.user_name.upcase %></h2>
<!-- form to edit user profile -->
<%= form_for(@user) do |f| %>
    <% if (current_user != nil && current_user.id == @user.id) ||
                  (current_user != nil && current_user.id == 1) %>
            <div class="form-group">
                <label>User Name</label>
                <%= f.text_field :user_name, placeholder: "Enter User Name", class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Email</label>
                <%= f.email_field :email, placeholder: "Enter Email", class: "form-control" %>    
            </div>
            <div class="form-group">
                <label>Password</label>
                <%= f.password_field :password, placeholder:"Password", class: "form-control" %>
            </div> 
            <div class="form-group">
                <label>Confirm Password</label>
                <%= f.password_field :password_confirmation, placeholder:"Confirm Password", class: "form-control" %>
            </div>
            <div class="form-group">
                <label>Profile Picture</label>
                <%= f.file_field :image, class: "picUpload"%>
            </div>
            <!-- submit button, create account -->
            <%= f.submit "UPDATE PROFILE", class: "submit" %> 
        <!-- delete profile, why would you do such a thing -->
        <%= link_to "Delete Profile", user_path, method: :delete, data: {   confirm: "Are you sure you want to delete this profile?"} %></br>
    <% end %>    
        <!-- back to video feed -->
    <%= link_to "Back to Feed", videos_path %>     
<% end %>

<div class="up">
    <%= link_to 'UPLOAD     ', new_video_path %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
</div> 

app/views/users/index.html.erb
<h2>KADETS</h2>

<!-- iterates through each user, making a user list -->
<% @users.each do |u| %>
	<div class="contain">
		<h3><%= image_tag u.image.url(:small), class:"idThumb" %>  <%= link_to u.user_name, user_path(u) %></h3>
		<%= link_to "Follow", followings_path( :follower_id => u), :method => :post %>
		<!-- only signed in user or admin can access edit for their profile -->
		<% if (current_user != nil && current_user.id == u.id) ||
			  (current_user != nil && current_user.id == 1) %>
			<%= link_to 'Edit Profile   ', edit_user_path(u.id) %>
			<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
		<% else %>	
			<!-- edit feature does not show	 -->
		<% end %>
	</div>
<% end %>
<!-- back to video feed -->
<%= link_to "Back to Feed", videos_path %>

<div class="up">
  <%= link_to 'UPLOAD     ', new_video_path %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
</div> 

app/views/users/new.html.erb
<h2>SIGN UP</h2>
<!-- form to create a new user account -->
<%= form_for(@user) do |f| %>
	<div class="form-group">
		<label>User Name</label>
		<%= f.text_field :user_name, placeholder: "Enter User Name", class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Email</label>
		<%= f.email_field :email, placeholder: "Enter Email", class: "form-control" %>    
	</div>
	<div class="form-group">
		<label>Password</label>
		<%= f.password_field :password, placeholder:"Password", class: "form-control" %>
	</div> 
	<div class="form-group">
		<label>Confirm Password</label>
		<%= f.password_field :password_confirmation, placeholder:"Confirm Password", class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Profile Picture</label>
		<%= f.file_field :image, class: "picUpload"%>
	</div>
	<!-- submit button, create account -->
	<%= f.submit "JOIN KILOS", class: "submit" %> 
	<!-- go to login screen -->
	<button class="submit" id="login"><%= link_to "LOGIN", new_session_path %></button>
<% end %>
<div class="up">
	<%= link_to 'BE OUR GUEST', videos_path %>
	<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
</div> 

app/views/users/show.html.erb
<!-- auto update current user name, put into uppercase -->
<h2><%= image_tag @user.image.url(:small), class:"idThumb" %>  <%= @user.user_name.upcase %></h2>
<!-- <p>Following</p>
<ul>
	<%# if @user.followings.exists? %>
		<%# @user.followings.each do |f| %>
			<li><%#= f.user_name %>
				<%#= link_to "Unfollow", f, :method => :delete %>
			</li>
		<% #end %>
	<%# end %>	
</ul>

<%#= link_to "followers", followings_path %>
	
<ul>
	<%# if @user.inverse_followers.user_id != nil %>
		<%# @user.inverse_followers.each do |f| %>
			<li><%#= f.user_name %>
			</li>
		<%# end %>
	<%# end %>
</ul>	 -->
<!-- iterates through each user video, placing it within a wrapper -->
<% @videos.each do |v| %>
	<div class="contain">
   		<div class="idStamp">
			<span class="idThumb"><%= image_tag v.user.image.url(:small) %></span>
			<%= link_to v.user.user_name, user_path(v.user) %>
			<span class="dateStamp"><%= v.updated_at.strftime("Uploaded %b %-d, %Y") %></span>
		</div>
   		<iframe src="https://www.youtube.com/embed/<%= YoutubeID.from(v.source) %>?modestbranding=1" frameborder="0" seamless></iframe>
   		<div class="textFrame">
     		<h3><%= link_to v.title, video_path(v) %></h3>
			<p><%= v.description %></p>
			<% if (current_user != nil && current_user.id == v.user_id) ||
			  	  (current_user != nil && current_user.id == 1) %>
				<%= link_to 'Edit Video   ', edit_video_path(v.id) %>
				<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
			<% else %>	
				<!-- edit option not visable -->	
			<% end %>
		</div>
	</div> 
<% end %>
<!-- links back to user list -->
<%= link_to 'Video Feed', videos_path %>
<div class="up">
	<%= link_to 'UPLOAD', new_video_path %>
	<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
</div> 

app/views/videos/edit.html.erb
<h2>EDIT POST</h2>
<!-- form to edit a video post -->
<!-- page is only available to the uploader and admin -->
<%= form_for @video do |v| %>
	<div class="form-group">
		<label>Source</label>
		<%= v.text_field :source, class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Title</label>
		<%= v.text_field :title, class: "form-control" %>    
	</div>
	<div class="form-group">
		<label>Description</label>
		<%= v.text_area :description, class: "form-control" %>
	</div> 
	<%= link_to "Delete video", video_path, method: :delete, data: { confirm: "Are you sure you want to delete this video?"} %> 
	<!-- Finished Editing -->
	<%= v.submit "DONE", class: "submit" %> 
	<!-- return to feed -->
	<button class="submit" id="login"><%= link_to "CANCEL", videos_path %></button>
<% end %>
<!-- link to video feed -->
<%= link_to "Back to list", videos_path %></br>

app/views/videos/index.html.erb
<h2>TRAINING VIDEO</h2>
<!-- iterates through each uploaded video into a formatted container -->
<% @videos.each do |video| %>
	<div class="contain">
		<!-- uploader profile picture, user name, and time uploaded-->
		<div class="idStamp">
			<span class="idThumb"><%= image_tag video.user.image.url(:small) %></span>
			<%= link_to video.user.user_name, user_path(video.user) %>
			<span class="dateStamp"><%= video.updated_at.strftime("Uploaded %b %-d, %Y") %></span>
		</div>
		<!-- video frame	 -->
		<iframe src="https://www.youtube.com/embed/<%= YoutubeID.from(video.source) %>?modestbranding=1" frameborder="0" seamless></iframe>
		<!-- video description -->
		<div class="textFrame">
			<h3><%= link_to video.title, video_path(video.id) %></h3>
			<p><%= video.description %></p>
			<!-- if the current user is signed are able to edit their own posts, or if the user is the admin -->
			<% if (current_user != nil && current_user.id == video.user_id) ||
				(current_user != nil && current_user.id == 1) %>
				<%= link_to 'Edit Video   ', edit_video_path(video.id) %>
				<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
			<% else %>	
				<!-- edit option not visable -->	
			<% end %>	
		</div>
	</div>
<% end %>
<div class="up">
  <%= link_to 'UPLOAD     ', new_video_path %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
</div>  

app/views/videos/new.html.erb
<h2>UPLOAD VIDEO</h2>
<!-- form for video upload -->
<%= form_for @video do |v| %>
	<div class="form-group">
		<label>Source</label>
		<%= v.text_field :source, placeholder: "www.source.com", class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Title</label>
		<%= v.text_field :title, placeholder: "Enter Title", class: "form-control" %>    
	</div>
	<div class="form-group">
		<label>Description</label>
		<%= v.text_area :description, placeholder:"Description", class: "form-control" %>
	</div> 
	<!-- upload vid -->
	<%= v.submit "UPLOAD", class: "submit" %> 
	<!-- back to feed -->
	<button class="submit" id="login"><%= link_to "CANCEL", videos_path %></button>
<% end %>
<!-- link to video feed -->
<%= link_to "Back to list", videos_path %></br>

app/views/videos/show.html.erb
<!-- auto update current user name, put into uppercase -->
<h4><%= @video.title.upcase %></h4>
<div class="contain">
	<!-- wrap around video content -->
	<div class="vidframe">
		<iframe src="https://www.youtube.com/embed/<%= YoutubeID.from(@video.source) %>?modestbranding=1" frameborder="0" seamless></iframe>
		<p><%= @video.description %></p>
		<!-- if the current user is signed are able to edit their own posts, or if the user is the admin -->
		<% if (current_user != nil && current_user.id == @video.user_id) ||
			(current_user != nil && current_user.id == 1) %>
			<%= link_to 'Edit Video   ', edit_video_path(@video.id) %>
			<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
		<% else %>
			<!-- edit option not visable -->
		<% end %>
	</div>
</div>
<!-- link back to video feed -->
<%= link_to "Back to Feed", videos_path %></br>
<div class="up">
  <%= link_to 'UPLOAD     ', new_video_path %>
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
</div>  